# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Test

on:
  push:
    branches:
      - main
      - devops-**
      - dev**
      - hotfix-**
  pull_request:
    branches: [ "main" ]

jobs:
    
  build:
    name: Build and test
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{matrix.os}}
    
    defaults:
      run:
        working-directory: ./src/

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3
      
      
    - name: Setup .NET 2.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 2.1.x

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
      
    - name: Test on .NET 2.1
      run: dotnet test -c Release -f netcoreapp2.1 --no-build --no-restore --verbosity normal

    - name: Test on .NET 3.1
      run: dotnet test -c Release -f netcoreapp3.1 --no-build --no-restore --verbosity normal

    - name: Test on .NET 6.0
      run: dotnet test -c Release -f net6.0 --no-build --no-restore --verbosity normal

    - name: Test on .NET Framework 4.7.2 (Windows only)
      if: matrix.os == 'windows-latest'
      run: dotnet test -c Release -f net472 --no-build --no-restore

    - name: Test on .NET Framework 4.8 (Windows only)
      if: matrix.os == 'windows-latest'
      run: dotnet test -c Release -f net48 --no-build --no-restore
